/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


#define ADC_BASE_ADDR				0x40012000UL
#define ADC_CR1_REG_OFFSET			0x04UL
#define ADC_CR1_REG_ADDR			(ADC_BASE_ADDR + ADC_CR1_REG_OFFSET)

#define RCC_BASE_ADDR         0x40023800UL
#define RCC_APB2_ENB_OFFSET   0x44UL
#define RCC_APB2_ENR_ADDR     (RCC_BASE_ADDR + RCC_APB2_ENB_OFFSET)

// Bit 定義
#define ADC_CR1_SCANBIT       8   // ADC_CR1 Bit 8
#define ADC1_ENBBIT           8   // RCC_APB2ENR Bit 8


int main(void)
{
    /* Loop forever */


	volatile uint32_t * const pRccApb2Enr = (uint32_t *) RCC_APB2_ENR_ADDR;
	volatile uint32_t * const pAdcCr1Reg = (uint32_t*) ADC_CR1_REG_ADDR;


	*pRccApb2Enr |= (1 << ADC1_ENBBIT);

	*pAdcCr1Reg |= (1 << ADC_CR1_SCANBIT) ;


	for(;;);
}
