/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

//參考自memory map RCC欄位
#define RCC_BASE_ADDR     0x40023800UL

#define RCC_CFGR_REG_OFFSET 0x08UL

#define RCC_CFGR_REG_ADDR   (RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET)

#define GPIOA_BASE_ADDR     0x40020000UL

#define RCC_AHB1ENR_OFFSET  0x30UL


int main(void)
{

	volatile uint32_t *pRccCfgrReg = (uint32_t*)RCC_CFGR_REG_ADDR;



	//1. 設定RCC configuration register (RCC_CFGR)，把MCO1的位置進行設定，讓他去抓HSI
	*pRccCfgrReg &= ~(0x3 <<21); //清空21跟22 的bit 剛好就是設置成HSI功能

	//把HSI頻率再除以4 預設是16/4 = 4 (24-26bit = 110)
	*pRccCfgrReg |= (1 << 25);
	*pRccCfgrReg |= (1 << 26);

	//2. 把PA8設定為AF0 mode，以便輸出MCO1 訊號

	//a. 把GPIOA的外設時鐘開起來
	volatile uint32_t  * const pRCCAhb1Enr = (uint32_t*)(RCC_BASE_ADDR + RCC_AHB1ENR_OFFSET);
	*pRCCAhb1Enr |= (1 << 0); //GPIOAEN

	//b.GPIOA pin 8 設為備用模式
	uint32_t * pGPIOModeReg = (uint32_t *)(GPIOA_BASE_ADDR + 0x00);
	*pGPIOModeReg &= ~(0x3 << 16); //clear
	*pGPIOModeReg |= (0x2 << 16);  //Alternate function mode

	//c. 將備用模式設置為mode 0 for PA8
	volatile uint32_t  * const pGPIOAAltFunHighReg = (uint32_t *)(GPIOA_BASE_ADDR + 0x24);
	*pGPIOAAltFunHighReg &= ~(0xf << 0);

    /* Loop forever */
	for(;;);
}
